### ISSUE TITLE
RFC: Anybody using this for web?

### ISSUE THREAD

**Issue by MichaelMarner** [MichaelMarner/dart-redux-remote-devtools#17]
I'm only really interested in Flutter for mobile, and not web. That said, this library could be useful for people using Flutter for web.

I'm interested in finding out how this works for web, how it can be improved, what the pain points are etc.

So, anybody using this for web?

**Comment by nickmeinhold** [comment]
Hey @MichaelMarner!, thanks for the awesome package!  

I got it going for web maybe a month back.  I think the only pain point I had was getting socketcluster_client dependency to work (that's yours too right?).  I saw you had a change to "Allow `platform` to opt for io or html platform" but I couldn't see how that worked so I just replaced all the references to IoSocketPlatform with HttpSocketPlatform then it compiled and was all good from there I think.

I couldn't figure out a way to use different mains with run configurations to easily switch using remotedevtools on and off. I tried having different directories for `webdev serve/build` but any directory that wasn't `web` caused problems. So I was just commenting out whether `lib/main.dart` or `lib/main_rdt.dart` was used by web/main.dart. I imagine there's a simple way to do it, I didn't put much time into it. 

That's all I can think of, hope it's useful!

**Comment by MichaelMarner** [comment]
Thanks for the feedback!

`socketcluster_client` isn't mine, but I agree that's probably where to start for improving this library. Adding support for automatic reconnects and other features that other SocketCluster clients support.

**Comment by nickmeinhold** [comment]
You're probably aware but `socketcluster_client` works out of the box for web now and the updated flutter tool makes multiple entry points no problem, so I think there are basically no pain points any more. 

Have you tried using your package with Mac apps?  I had to add an entitlement, as described here: [OS Error: Operation not permitted](https://github.com/google/flutter-desktop-embedding/issues/546) but then it works beautifully!

**Comment by MichaelMarner** [comment]
Thanks again for the feedback @nickmeinhold - I'm going to close this issue now as it seems we don't really need to do anything more to support the web.

Anybody reading this - please create a new issue if you run into problems using this package! :)
