### ISSUE TITLE
Support for ACTION events

### ISSUE THREAD

**Issue by kadza** [MichaelMarner/dart-redux-remote-devtools#7]
Hi again,

it seems that dispatching an action from the dev tools app isn't supported. Do you plan to add it?

**Comment by MichaelMarner** [comment]
Time travel actions from devtools are supported if you are using a `DevToolsStore` for your store, from the `redux_dev_tools` package:

https://pub.dartlang.org/packages/redux_dev_tools

However you are right, sending arbitrary actions from devtools to the flutter app is currently not supported. I would be interested in adding this feature, but don't have a good approach yet.

The difficulty is that any actions from devtools will be a JSON object, and we would need to know how to convert the JSON to the correct Action objects to pass to redux. Happy to have the discussions on good ways to do that.

**Comment by MichaelMarner** [comment]
I think as a first step we could add an optional ActionDecoder parameter to our middleware that can be used to convert json to actions.

```
abstract class ActionDecoder {
  /// Converts a json object received from DevTools into an action
  dynamic decode(Map json);
}
```

At least adding this will allow Flutter app developers to provide their own implementation for their own actions.
